from models.base import Base
from models.cartao import Cartao
from models.cobranca import Cobranca
from models.funcionario import Funcionario
from models.loja import Loja
from models.pokemon import Pokemon
from models.produto import Produto
from models.tratamento import Tratamento
from models.treinador import Treinador
from models.centro_has_produto import Centro_has_produto
from models.funcionario_has_centro import Funcionario_has_centro
from models.tratamento_has_centro import Tratamento_has_centro